'use client';
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/WmTRNwziyD2
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Cabin } from 'next/font/google'
import { Rethink_Sans } from 'next/font/google'

cabin({
  subsets: ['latin'],
  display: 'swap',
})

rethink_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import Link from 'next/link';
import { useState } from 'react';

export function LayoutComponentV0() {
  const [isSidebarOpen, setIsSidebarOpen] = useState(false);

  const links = [
    {t:'Release Date', h:'/release-date'},
    {t:'Track Number', h:'/track-number'},
    {t:'Metrics Over Time', h:'/metrics-over-time'},
    {t:'Metrics By Album Size', h:'/metrics-by-album-size'},
    {t:'Album', h:'/album-gap'},
    {t:'Popularidade', h:'/duration-popularity'},
  ];

  return (
    <div className="flex flex-col w-full min-h-screen bg-[#0D9D55] dark:bg-[#0B7B43]">
      <header className="bg-[#0D9D55] dark:bg-[#0B7B43] shadow">
        <div className="container mx-auto py-6 px-4 md:px-6 lg:px-8">
          <div className="flex items-center justify-between">
            <div>
              <h1 className="text-3xl font-bold text-white">
                Análise de dataset de músicas do Spotify
              </h1>
              <p className="text-gray-200 mt-2">
                Trabalho final de Visualização de Dados - 2024/1
              </p>
            </div>
            <button
              className="md:hidden text-white hover:text-gray-300 transition-colors"
              type="button"
              onClick={() => setIsSidebarOpen(!isSidebarOpen)}
            >
              <MenuIcon className="h-6 w-6" />
              <span className="sr-only">Toggle sidebar</span>
            </button>
          </div>
        </div>
      </header>
      <div className="flex-1 container mx-auto py-8 px-4 md:px-6 lg:px-8 flex gap-8">
        <div
          className={`bg-white dark:bg-[#2C2C2C] rounded-lg shadow-lg p-8 ${
            isSidebarOpen ? 'block' : 'hidden'
          } md:block`}
        >
          <div className="flex items-center justify-between mb-4">
            <h2 className="text-lg font-bold text-[#0D9D55]">Visualizações</h2>
          </div>
          <ul className="space-y-2">
            {links.map((l) => (
              <li key={l.h}>
                <Link
                  className="block text-gray-700 dark:text-gray-300 hover:text-[#0D9D55] transition-colors"
                  href={l.h}
                >
                  {l.t}
                </Link>
              </li>
            ))}
          </ul>
        </div>
        <div className="flex-1">
          <Card>
            <CardHeader>
              <CardTitle>Revenue Trends</CardTitle>
            </CardHeader>
            <CardContent>
              <LineChart className="aspect-[16/9]" />
            </CardContent>
          </Card>
        </div>
        {/* <div className="flex-1 grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-8">
          <Card>
            <CardHeader>
              <CardTitle>Revenue Trends</CardTitle>
            </CardHeader>
            <CardContent>
              <LineChart className="aspect-[16/9]" />
            </CardContent>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle>Sales by Product</CardTitle>
            </CardHeader>
            <CardContent>
              <BarChart className="aspect-[16/9]" />
            </CardContent>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle>Customer Acquisition</CardTitle>
            </CardHeader>
            <CardContent>
              <LineChart className="aspect-[16/9]" />
            </CardContent>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle>Customer Retention</CardTitle>
            </CardHeader>
            <CardContent>
              <LineChart className="aspect-[16/9]" />
            </CardContent>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle>Sales Funnel</CardTitle>
            </CardHeader>
            <CardContent>
              <LineChart className="aspect-[16/9]" />
            </CardContent>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle>Top Performing Regions</CardTitle>
            </CardHeader>
            <CardContent>
              <BarChart className="aspect-[16/9]" />
            </CardContent>
          </Card>
        </div> */}
      </div>
    </div>
  );
}

function BarChart(props) {
  return <div {...props}>Gráfico de barras</div>;
}

function LineChart(props) {
  return <div {...props}>Gráfico de linhas</div>;
}

function MenuIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  );
}
