/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/WmTRNwziyD2
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Cabin } from 'next/font/google'
import { Rethink_Sans } from 'next/font/google'

cabin({
  subsets: ['latin'],
  display: 'swap',
})

rethink_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Drawer from "./Drawer";
import NavButton from "./NavButton";

const links = [
  { t: "Release Date", h: "/release-date" },
  { t: "Track Number", h: "/track-number" },
  { t: "Metrics Over Time", h: "/metrics-over-time" },
  { t: "Metrics By Album Size", h: "/metrics-by-album-size" },
  { t: "Album", h: "/album-gap" },
  { t: "Popularidade", h: "/duration-popularity" },
  { t: "Correlations", h: "/correlations" },
];

export function LayoutComponent({ children }) {
  return (
    <div className="flex flex-col w-full min-h-screen bg-[#242424] dark:bg-[#242424]">
      <header className="bg-[#121212] dark:bg-[#121212] shadow">
        <div className="container mx-auto py-6 px-4 md:px-6 lg:px-8">
          <div className="flex items-center justify-between">

            <div className=" flex items-center justify-center">
              <div className="mr-4">
                <img src="https://img.icons8.com/?size=100&id=11116&format=png&color=FFFFFF"   className="w-12" />
              </div>

              <div>
              <h1 className="text-xl font-bold text-white">
                Análise de Dados no Spotify
              </h1>
              <p className="text-[13px] text-gray-200 mt-0">
                Fatores de Sucesso de Artistas e Músicas na Era do Streaming
              </p>
            </div>
            </div>

            <NavButton />
          </div>
        </div>
      </header>
      <div className="flex-1 container mx-auto py-8 px-4 md:px-6 lg:px-8 flex gap-8">
        <Drawer links={links} />
        <div className="flex-1">{children}</div>
      </div>
    </div>
  );
}

